# Generated by Django 4.1 on 2022-08-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HWStockApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.CharField(blank=True, choices=[('C', 'Construccion'), ('P', 'Pintura'), ('B', 'Bannos'), ('M', 'Madera'), ('H', 'Hogar'), ('J', 'Jardin'), ('E', 'Electricidad'), ('O', 'Otros')], max_length=1),
        ),
    ]
