# Generated by Django 4.1 on 2022-08-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HWStockApp', '0002_productos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
