# Generated by Django 4.1 on 2022-08-28 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRApp', '0002_cliente_user_id_empleado_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
