# Generated by Django 4.1 on 2022-08-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRApp', '0003_alter_cliente_password_alter_cliente_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
