# Generated by Django 4.1 on 2022-08-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRApp', '0004_remove_empleado_user_id_empleado_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.IntegerField(null=True),
        ),
    ]
