# Generated by Django 4.1 on 2022-08-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRApp', '0005_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
