# Generated by Django 4.1 on 2022-08-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRApp', '0006_alter_cliente_telefono_alter_empleado_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='user_id',
            new_name='user',
        ),
    ]
