# Generated by Django 4.1 on 2022-08-28 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRApp', '0007_rename_user_id_cliente_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='nombre',
        ),
    ]
