# Generated by Django 4.1 on 2022-08-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRApp', '0008_remove_cliente_apellido_remove_cliente_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombre_usuario',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='horario',
            field=models.CharField(blank=True, choices=[('M', 'Matutino'), ('V', 'Vespertino')], max_length=1),
        ),
    ]
