# Generated by Django 4.1 on 2022-08-28 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRApp', '0009_remove_cliente_nombre_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='user',
            new_name='user_id',
        ),
    ]
