# Generated by Django 4.1 on 2022-08-29 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRApp', '0010_rename_user_cliente_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
